# logfilename                                    [owner:group] mode count size(KB) when  flags
/Users/*/.codex/s3-archive/logs/hook-stop.log                  644  7     10240    *     J
/Users/*/.codex/s3-archive/logs/daemon.stdout.log              644  7     10240    *     J
/Users/*/.codex/s3-archive/logs/daemon.stderr.log              644  7     10240    *     J
